version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - "8090:8080"     # Jenkins web UI
      - "50000:50000"   # Agent communication
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Let Jenkins control Docker
      - ../:/workspace                           # Mount your NewsWave project into Jenkins workspace
volumes:
  jenkins_home:
